---
- name: Restart Wazuh_manager
  become: true
  become_user: '{{ wazuh_manager_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ wazuh_manager_container }}'
    scope: user
