---
- name: Ensure Guacamole web is running
  become: true
  become_user: '{{ guacamole_web_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ guacamole_web_container }}'
    scope: user
