- name: Restart Oauth2-Proxy
  become: true
  become_user: "{{ oauth2_proxy_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ oauth2_proxy_container }}"
    scope: user
