---
- name: Ensure there's a directory to Technitium config
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ technitium_config }}"
    podman_user: "{{ technitium_user }}"
