---
- name: Create Technitium DNS server Quadlet file
  become: true
  become_user: '{{ technitium_user }}'
  notify: Restart technitium
  containers.podman.podman_container:
    name: '{{ technitium_container }}'
    image: docker.io/technitium/dns-server:latest
    state: quadlet
    quadlet_filename: '{{ technitium_container }}'
    ports:
      - '5380:5380/tcp'
      - '53:53/tcp'
      - '53:53/udp'
    volumes:
      - '{{ technitium_config }}:/config:z'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      DNS_SERVER_ADMIN_PASSWORD: '{{ technitium_web_password }}'
      DNS_SERVER_FORWARDERS: 1.1.1.1, 8.8.8.8
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=5
      - |
        [Install]
        WantedBy=default.target multi-user.target
