---
- name: Create headscale Quadlet file
  become: true
  become_user: '{{ headscale_user }}'
  notify: Restart Headscale
  containers.podman.podman_container:
    name: '{{ headscale_container }}'
    image: docker.io/headscale/headscale:stable
    state: quadlet
    quadlet_filename: '{{ headscale_container }}'
    command: '{{ headscale_command }}'
    network: '{{ headscale_network | default(omit) }}'
    # ports:
    #   - '{{ headscale_http_port }}:8080'
    #   - '{{ headscale_metrics_port }}:9090'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
    volumes:
      - '{{ headscale_conf_dir }}:/etc/headscale:z'
      - '{{ headscale_tls_vol }}:/var/lib/headscale:z'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=10
      - |
        [Install]
        WantedBy=default.target multi-user.target
