---
- name: Restart Caddy
  become: true
  become_user: "{{ caddy_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ caddy_container }}"
    scope: user
