---
- name: Restart tdarr
  become: true
  become_user: '{{ tdarr_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ tdarr_container }}'
    scope: user
