- name: Configure torrenting virtual machine
  hosts: torrent
  vars:
    torrent_user: torrent
    torrent_downloads: /var/torrents

  tasks:
    - name: NFS volumes configuration
      ansible.builtin.import_role:
        name: nfs_client
      vars:
        nfs_client_user: "{{ torrent_user }}"
        nfs_client_mounts:
          { "{{nas_host}}:{{ nfs_server_data }}/torrents": "{{ torrent_downloads }}" }

    - name: Ensure there's a directory to store Qbittorrent Data
      ansible.builtin.import_role:
        name: podman
        tasks_from: local_volume
      vars:
        podman_local_volume: /var/qbittorrent
        podman_user: "{{ torrent_user }}"

    - name: Deploy Qbittorrent
      ansible.builtin.import_role:
        name: qbittorrent
      vars:
        qbittorrent_user: "{{ torrent_user }}"
        qbittorrent_container: qbittorrent
        qbittorrent_data: /var/qbittorrent
        qbittorrent_downloads: "{{ torrent_downloads }}"
