- name: Configure base dependencies for all virtual machines
  hosts: all, !hypervisors, !firewall
  tasks:
    - name: Generate /etc/hosts from template
      ansible.builtin.import_role:
        name: dynamic_hosts
    - name: General virtual machine configuration
      ansible.builtin.import_role:
        name: base_vm
