---
- name: Install packages
  ansible.builtin.import_tasks: packages.yml

- name: Configure performance options
  ansible.builtin.import_tasks: performance.yml

- name: Ensure qemu-guest-agent is running and starts on boot
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: qemu-guest-agent

# Usernames are the same as hostnames for my virtual machines
- name: Ensure lingering is enabled
  become: true
  ansible.builtin.command: "loginctl enable-linger {{ ansible_hostname }}"
  changed_when: false
