---
- name: Ensure tdarr is running
  become: true
  become_user: '{{ tdarr_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ tdarr_container }}'
    scope: user
