---
- name: Create Guacd Quadlet file
  become: true
  become_user: '{{ guacamole_guacd_user }}'
  notify: Restart Guacd
  containers.podman.podman_container:
    name: '{{ guacamole_guacd_container }}'
    image: docker.io/guacamole/guacd:latest
    state: quadlet
    quadlet_filename: '{{ guacamole_guacd_container }}'
    ports:
      - '{{ guacamole_guacd_port | default(4822) }}:4822'
    network: '{{ guacamole_guacd_network | default(omit) }}'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Install]
        WantedBy=default.target multi-user.target
