---
- name: Restart Tailscale client
  become: true
  become_user: '{{ tailscale_client_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ tailscale_client_container }}'
    scope: user
