---
dynamic_hosts_map:
  10.0.1.10: bastion.vm
  10.0.8.10: code.vm
  10.0.1.1: firewall.vm
  10.0.11.10: nas.vm
  10.0.10.10: servarr.vm
  10.0.4.10: proxy.vm
  10.0.7.2: dns.vm
  10.0.0.19: streaming.vm
  10.0.6.10: torrent.vm
  10.0.1.254: hypervisor.vm
  10.0.0.10: security.vm
  10.0.0.11: sandbox.vm
  10.0.0.13: knowledge.vm
