---
- name: Create code-server directories if needed
  become: true
  ansible.builtin.file:
    path: "/home/{{ security_user }}/{{ security_code_directory }}"
    state: directory
    mode: "0755"
    owner: "{{ security_user }}"
    group: "{{ security_user }}"

- name: Create Vaultwarden directories if needed
  become: true
  ansible.builtin.file:
    path: "{{ security_vaultwarden_data }}"
    state: directory
    mode: "0755"
    owner: "{{ security_user }}"
    group: "{{ security_user }}"

- name: Create Postgres directories if needed
  become: true
  ansible.builtin.file:
    path: "{{ security_postgres_data }}"
    state: directory
    mode: "0755"
    owner: "{{ security_user }}"
    group: "{{ security_user }}"
