- name: Enable ipv4 forwarding
  become: true
  ansible.posix.sysctl:
    name: 'net.ipv4.ip_forward'
    value: '1'
    state: present

- name: Enable ipv6 forwarding
  become: true
  ansible.posix.sysctl:
    name: 'net.ipv6.conf.all.forwarding'
    value: '1'
    state: present
