---
- name: Install zram packages for Debian
  ansible.builtin.include_tasks: zram-debian.yml
  when: ansible_os_family == "Debian"

- name: Install zram packages for Almalinux
  ansible.builtin.include_tasks: zram-almalinux.yml
  when: ansible_os_family == "RedHat"

- name: Copy zram configuration file
  become: true
  ansible.builtin.copy:
    src: zram-generator.conf
    dest: /etc/systemd/zram-generator.conf
    owner: root
    group: root
    mode: '0644'

- name: Load zstd module
  become: true
  community.general.modprobe:
    name: zstd
    state: present
    persistent: present

- name: Load zram module
  become: true
  community.general.modprobe:
    name: zram
    state: present
    persistent: present


- name: Ensure zram device starts on boot and is active
  become: true
  ansible.builtin.systemd_service:
    state: started
    daemon_reload: true
    name: /dev/zram0

- name: Ensure there's a high swappiness value
  become: true
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '60'
    state: present
