---
- name: Restart lidatube
  become: true
  become_user: "{{ lidatube_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ lidatube_container }}"
    scope: user
