---
- name: Configure network
  ansible.builtin.include_tasks: network.yml

- name: Package configuration
  ansible.builtin.include_tasks: packages.yml

- name: OpenRGB Deployment
  ansible.builtin.include_tasks: openrgb.yml

- name: Performance tuning
  ansible.builtin.include_tasks: performance.yml
