---
- name: Network configuration
  ansible.builtin.include_tasks: network.yml

- name: Configure webui access
  ansible.builtin.include_tasks: webui.yml

- name: Package configuration
  ansible.builtin.include_tasks: packages.yml

- name: OpenRGB Deployment
  ansible.builtin.include_tasks: openrgb.yml

- name: Performance tuning
  ansible.builtin.include_tasks: performance.yml

- name: Services configuration
  ansible.builtin.include_tasks: services.yml
