---
- name: Update package cache
  become: true
  ansible.builtin.package:
    update_cache: true

- name: Install tuned
  become: true
  ansible.builtin.package:
    name: tuned
    state: present

- name: Install web tools
  become: true
  ansible.builtin.package:
    name:
      - curl
      - wget
    update_cache: true

- name: Install dns utilities
  become: true
  ansible.builtin.package:
    name: dnsutils
    update_cache: true

- name: Install text editors
  become: true
  ansible.builtin.package:
    name:
      - nano
      - vim
    state: present

- name: Install virtualization tools
  become: true
  ansible.builtin.package:
    name:
      - libvirt
    state: present