- name: Install Cockpit and its extensions
  become: true
  ansible.builtin.package:
    name:
      - cockpit-*

- name: Enable cockpit service and ensure it is running
  become: true
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: true
    state: started
    masked: false
  with_items:
    - cockpit
    - cockpit.socket

- name: Copy cockpit configuration file
  become: true
  ansible.builtin.copy:
    src: files/cockpit.conf
    dest: /etc/cockpit/cockpit.conf
    mode: '0644'
  notify: Restart cockpit
