- name: Install Cockpit and its extensions
  become: true
  ansible.builtin.package:
    name:
      - cockpit-*

- name: Enable cockpit service and ensure it is running
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: true
    state: started
    masked: false
  with_items:
    - cockpit
    - cockpit.socket
