---
- name: Ensure there's a directory to store Lidarr configuration
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ lidarr_config }}"
    podman_user: "{{ lidarr_user }}"

- name: Ensure there's a directory to access raw downloads
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ lidarr_downloads }}"
    podman_user: "{{ lidarr_user }}"

- name: Ensure there's a directory to access music collection
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ lidarr_collection }}"
    podman_user: "{{ lidarr_user }}"
