---
- name: Ensure there's a volume to store Vaultwarden data
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ vaultwarden_data }}'
    podman_user: '{{ vaultwarden_user }}'
