---
- name: Package configuration
  ansible.builtin.import_tasks: packages.yml
- name: Directory configuration
  ansible.builtin.import_tasks: directories.yml
- name: Profiles configuration
  ansible.builtin.import_tasks: files.yml
- name: Modules configuration
  ansible.builtin.import_tasks: modules.yml
- name: Service configuration
  ansible.builtin.import_tasks: services.yml
- name: OpenRGB Deployment
  ansible.builtin.import_tasks: openrgb.yml
