---
- name: Ensure OpenRGB is running and starts on boot
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: openrgb
    enabled: true

- name: Ensure rgbon timer is enabled and running
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: rgbon.timer
    enabled: true

- name: Ensure rgboff timer is enabled and running
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: rgboff.timer
    enabled: true
