---
- name: Ensure Flaresolverr is running
  become: true
  become_user: "{{ servarr_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ servarr_flaresolverr_container_name }}"
    scope: user

- name: Ensure Prowlarr is running
  become: true
  become_user: "{{ servarr_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ servarr_prowlarr_container_name }}"
    scope: user

- name: Ensure Lidarr is running
  become: true
  become_user: "{{ servarr_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ servarr_lidarr_container_name }}"
    scope: user
