---
- name: Ensure there's a directory to access Wazuh manager certs
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ wazuh_manager_ssl_certs_dir }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a directory to access Wazuh manager configuration
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ wazuh_manager_config_dir }}'
    podman_user: '{{ wazuh_manager_user }}'
