---
- name: Allow usage of privileged ports by rootless processes
  ansible.builtin.import_role:
    name: podman
    tasks_from: rootless_ports
- name: Directories configuration
  ansible.builtin.import_tasks: directories.yml
- name: Ensure configuration file is present
  ansible.builtin.import_tasks: config.yml
- name: Volumes configuration
  ansible.builtin.import_tasks: volumes.yml
- name: Quadlet configuration
  ansible.builtin.import_tasks: quadlets.yml
- name: Services configuration
  ansible.builtin.import_tasks: services.yml
