---
- name: Ensure Wazuh Manager is running
  become: true
  become_user: '{{ wazuh_manager_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ wazuh_manager_container }}'
    scope: user
