---
- name: Restart Headscale
  become: true
  become_user: '{{ headscale_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ headscale_container }}'
    scope: user
