---
- name: Ensure Oauth2-Proxy is running
  become: true
  become_user: "{{ oauth2_proxy_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: "{{ oauth2_proxy_container }}"
    scope: user
