---
- name: Restart Postgres
  become: true
  become_user: '{{ postgres_podman_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ postgres_container }}'
    scope: user
