---
- name: Volumes configuration
  when: postgres_data_vol is defined
  ansible.builtin.import_tasks: volumes.yml
- name: Prepare directories to be bind
  when: postgres_data_dir is defined
  ansible.builtin.import_tasks: bind_mounts.yml
- name: Quadlet configuration
  ansible.builtin.import_tasks: quadlet.yml
- name: Services configuration
  ansible.builtin.import_tasks: services.yml
