---
- name: Ensure Flaresolverr is running
  become: true
  become_user: "{{ flaresolverr_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ flaresolverr_container }}"
    scope: user
