- name: Restart networking
  become: true
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

- name: Restart cockpit
  become: true
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - cockpit
    - cockpit.socket
