---
- name: Restart wazuh_indexer
  become: true
  become_user: '{{ wazuh_indexer_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ wazuh_indexer_container }}'
    scope: user
