---
- name: Create A records
  community.general.cloudflare_dns:
    zone: '{{ cloudflare_dns_zone }}'
    record: '{{ item.record }}'
    type: A
    value: '{{ item.value }}'
    comment: '{{ item.comment | default(omit) }}'
    api_token: '{{ cloudflare_dns_token }}'
  loop: '{{ cloudflare_dns_data }}'
