---
- name: Enable cockpit service and ensure it is running
  become: true
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: true
    state: started
    masked: false
  with_items:
    - cockpit
    - cockpit.socket

- name: Ensure cockpit collects metrics
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: pmlogger.service
    enabled: true
