---
- name: Ensure tuned service is active and running
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: tuned

- name: Apply tuned profile for qemu_kvm
  become: true
  changed_when: false
  ansible.builtin.shell:
    cmd: tuned-adm profile virtual-host
