---
- name: Ensure Lidatube is running
  become: true
  become_user: '{{ lidatube_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ lidatube_container }}'
    scope: user
