---
- name: Ensure NFS dependencies are present
  ansible.builtin.import_role:
    name: nfs
    tasks_from: client.yml

- name: Unmount NFS volumes to prevent data corruption
  become: true
  ansible.posix.mount:
    src: "{{ nas_host }}:{{ nas_data }}/{{ mountpoint }}"
    path: "/var/{{ mountpoint }}"
    opts: rw,sync,hard
    state: unmounted
    fstype: nfs
  loop: "{{ wikijs_nas_mountpoints }}"
  loop_control:
    loop_var: mountpoint

- name: Delete NFS mountpoints to prevent messing up with permissions
  become: true
  ansible.builtin.file:
    path: "/var/{{ item }}"
    state: absent
    mode: '0777'
  with_items: "{{ wikijs_nas_mountpoints }}"

- name: Ensure mountpoints for NFS exist and have the right permissions
  become: true
  ansible.builtin.file:
    path: "/var/{{ item }}"
    owner: "{{ wikijs_user }}"
    group: "{{ wikijs_user }}"
    state: directory
    mode: '0777'
  with_items: "{{ wikijs_nas_mountpoints }}"

- name: Ensure NFS volumes are mounted again
  become: true
  ansible.posix.mount:
    src: "{{ nas_host }}:{{ nas_data }}/{{ mountpoint }}"
    path: "/var/{{ mountpoint }}"
    opts: rw,sync,hard
    state: mounted
    boot: true
    fstype: nfs
  loop: "{{ wikijs_nas_mountpoints }}"
  loop_control:
    loop_var: mountpoint
