---
- name: Ensure wikijs is running
  become: true
  become_user: "{{ wikijs_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: "{{ wikijs_container }}"
    scope: user
