---
- name: Ensure there's a directory to store Qbittorrent Configuration
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ qbittorrent_data }}'
    podman_user: '{{ qbittorrent_user }}'

- name: Ensure there's a directory to store Qbittorrent downloads
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ qbittorrent_downloads }}'
    podman_user: '{{ qbittorrent_user }}'
