---
- name: Import Wazuh gpg key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: Add Wazuh repository
  become: true
  ansible.builtin.yum_repository:
    name: wazuh
    description: EPEL YUM repo
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    baseurl: https://packages.wazuh.com/{{ wazuh_agent_version }}/yum/
    protect: true
