---
- name: Ensure there's a directory to store Prowlarr configuration
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ prowlarr_config }}"
    podman_user: "{{ prowlarr_user }}"
