---
- name: Ensure Prowlarr is running
  become: true
  become_user: '{{ prowlarr_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ prowlarr_container }}'
    scope: user
