---
- name: Volumes configuration
  ansible.builtin.import_tasks: volumes.yml
- name: Prepare directories to be bind
  ansible.builtin.import_tasks: bind_mounts.yml
- name: Quadlet files configuration
  ansible.builtin.include_tasks: quadlets.yml
- name: Services configuration
  ansible.builtin.include_tasks: services.yml
