---
- name: Ensure Navidrome is running
  become: true
  become_user: "{{ navidrome_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: "{{ navidrome_container }}"
    scope: user
