---
- name: Ensure there's a directory to store Navidrome configuration
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ navidrome_config }}"
    podman_user: "{{ navidrome_user }}"
