---
- name: Create Guacamole web Quadlet file
  become: true
  become_user: '{{ guacamole_web_user }}'
  notify: Restart Guacamole web
  containers.podman.podman_container:
    name: '{{ guacamole_web_container }}'
    image: docker.io/guacamole/guacamole:latest
    state: quadlet
    quadlet_filename: '{{ guacamole_web_container }}'
    ports:
      - '{{ guacamole_web_port | default(8080) }}:8080'
    network: '{{ guacamole_web_network | default(omit) }}'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      GUACD_HOSTNAME: '{{ guacamole_web_guacd_hostname }}'
      GUACD_PORT: '{{ guacamole_web_guacd_port | default(4822) }}'
      POSTGRESQL_HOSTNAME: '{{ guacamole_web_pg_host }}'
      POSTGRESQL_DATABASE: '{{ guacamole_web_pg_db }}'
      POSTGRESQL_PORT: '{{ guacamole_web_pg_port | default(5432) }}'
      POSTGRESQL_USER: '{{ guacamole_web_pg_user }}'
      POSTGRESQL_PASSWORD: '{{ guacamole_web_pg_pass }}'
    command: start
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Install]
        WantedBy=default.target multi-user.target
