- name: Ensure Vaultwarden is running
  become: true
  become_user: "{{ vaultwarden_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: "{{ vaultwarden_container }}"
    scope: user
