---
- name: Update package cache
  become: true
  ansible.builtin.package:
    update_cache: true

- name: Install web tools
  become: true
  ansible.builtin.package:
    name:
      - wget
      - curl
    state: present

- name: Install text editors
  become: true
  ansible.builtin.package:
    name:
      - vim
      - nano
    state: present

- name: Install misc tools
  become: true
  ansible.builtin.package:
    name:
      - tuned
      - qemu-guest-agent
      - telnet
    state: present

- name: Install SELinux libraries
  become: true
  when: ansible_os_family == "Almalinux"
  ansible.builtin.package:
    name:
      - python3-libselinux
    state: present
