---
- name: Ensure code-server is running
  become: true
  become_user: "{{ code_server_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: "{{ code_server_container }}"
    scope: user
