---
- name: Ensure NFS dependencies are present
  ansible.builtin.import_role:
    name: nas
    tasks_from: client.yml

- name: Ensure mountpoints for NFS exist
  become: true
  ansible.builtin.file:
    path: "/var/{{ item }}"
    owner: "{{ knowledge_user }}"
    group: "{{ knowledge_user }}"
    state: directory
    mode: '0777'
  with_items: "{{ knowledge_nas_mountpoints }}"

- name: Ensure NFS volumes are mounted
  become: true
  ansible.posix.mount:
    src: "{{ nas_host }}:{{ nas_data }}/{{ mountpoint }}"
    path: "/var/{{ mountpoint }}"
    opts: rw,sync,hard
    state: mounted
    boot: true
    fstype: nfs
  loop: "{{ knowledge_nas_mountpoints }}"
  loop_control:
    loop_var: mountpoint
