---
- name: Restart Guacamole web
  become: true
  become_user: '{{ guacamole_web_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: '{{ guacamole_web_container }}'
    scope: user
