---
- name: Bind mounts configuration
  ansible.builtin.import_tasks: directories.yml
- name: Ensure configuration files are present
  ansible.builtin.import_tasks: config.yml
- name: Allow usage of privileged ports by rootless processes
  ansible.builtin.import_role:
    name: podman
    tasks_from: rootless_ports
- name: Quadlet(s) configuration
  ansible.builtin.import_tasks: quadlets.yml
- name: Services configuration
  ansible.builtin.import_tasks: services.yml
