---
- name: Create Blocky DNS server Quadlet file
  become: true
  become_user: '{{ blocky_user }}'
  notify: Restart blocky
  containers.podman.podman_container:
    name: '{{ blocky_container }}'
    image: docker.io/spx01/blocky:latest
    state: quadlet
    quadlet_filename: '{{ blocky_container }}'
    ports:
      - '{{ blocky_http_port | default(4000) }}:4000/tcp'
      - '{{ blocky_dns_port | default(53) }}:53/tcp'
      - '{{ blocky_dns_port | default(53) }}:53/udp'
    volumes:
      - '{{ blocky_config_dir }}/config.yml:/app/config.yml:z'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=5
      - |
        [Install]
        WantedBy=default.target multi-user.target
