- name: Restart Vaultwarden
  become: true
  become_user: "{{ vaultwarden_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ vaultwarden_container }}"
    scope: user
