- name: Configure podman
  ansible.builtin.import_role:
    name: podman

- name: Allow usage of privileged ports by rootless processes
  ansible.builtin.import_role:
    name: podman
    tasks_from: rootless_ports
