---
- name: Ensure there's a directory to store Headscale configuration
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ headscale_conf_dir }}'
    podman_user: '{{ headscale_user }}'
