---
- name: Copy Wazuh Indexer configuration file
  become: true
  ansible.builtin.copy:
    src: files/wazuh.indexer.yml
    dest: '{{ wazuh_indexer_config_dir }}/wazuh.indexer.yml'
    owner: '{{ wazuh_indexer_user }}'
    group: '{{ wazuh_indexer_user }}'
    mode: '0777'

- name: Copy Wazuh Indexer configuration users file
  become: true
  ansible.builtin.template:
    src: templates/internal_users.yml.j2
    dest: '{{ wazuh_indexer_config_dir }}/internal_users.yml'
    owner: '{{ wazuh_indexer_user }}'
    group: '{{ wazuh_indexer_user }}'
    mode: '0777'
