---
- name: Ensure there's a directory to access Wazuh indexer certs
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ wazuh_indexer_tls_dir }}'
    podman_user: '{{ wazuh_indexer_user }}'

- name: Ensure there's a directory to store Wazuh Indexer config
  become: true
  ansible.builtin.file:
    path: '{{ wazuh_indexer_config_dir }}'
    owner: '{{ wazuh_indexer_user }}'
    group: '{{ wazuh_indexer_user }}'
    state: directory
    mode: '0777'
