---
- name: Ensure there's a directory to store wazuh certificates
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ wazuh_indexer_tls_dir }}'
    podman_user: '{{ wazuh_indexer_user }}'

- name: Run Wazuh certificate generator container
  containers.podman.podman_container:
    name: wazuh_indexer_generator
    image: wazuh/wazuh-certs-generator:0.0.2
    volume:
      - '{{ wazuh_indexer_tls_dir }}:/certificates'
    state: started
    env:
      TZ: '{{ tz }}'
