---
- name: Ensure there's a directory to store wazuh certificates
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ wazuh_indexer_tls_dir }}'
    podman_user: '{{ wazuh_indexer_user }}'

- name: Ensure there's a directory to store wazuh certificate generator config
  ansible.builtin.import_role:
    name: podman
    tasks_from: bind_mount
  vars:
    podman_bind_mount: '{{ wazuh_indexer_tls_conf_dir }}'
    podman_user: '{{ wazuh_indexer_user }}'

- name: Copy Wazuh certificate configuration
  become: true
  ansible.builtin.template:
    src: 'templates/certs.yml.j2'
    dest: '{{ wazuh_indexer_conf_dir }}/certs.yml'
    owner: '{{ wazuh_indexer_user }}'
    group: '{{ wazuh_indexer_group }}'
    mode: '0777'

- name: Run Wazuh certificate generator container
  become: true
  become_user: '{{ wazuh_indexer_user }}'
  containers.podman.podman_container:
    name: wazuh_indexer_generator
    image: docker.io/wazuh/wazuh-certs-generator:0.0.2
    volume:
      - '{{ wazuh_indexer_tls_dir }}:/certificates:z'
      - '{{ wazuh_indexer_tls_dir }}/certs.yml:/config/certs.yml:z'
    state: started
    env:
      TZ: '{{ tz }}'
      PUID: '1000'
      PGID: '1000'
