---
- name: Create Wazuh Indexer Quadlet file
  become: true
  become_user: '{{ wazuh_indexer_user }}'
  notify: Restart wazuh_indexer
  containers.podman.podman_container:
    name: '{{ wazuh_indexer_container }}'
    image: docker.io/wazuh/wazuh-indexer:{{ wazuh_indexer_version }}
    network: '{{ wazuh_indexer_network }}'
    hostname: '{{ wazuh_indexer_hostname }}'
    state: quadlet
    quadlet_filename: '{{ wazuh_indexer_container }}'
    ports:
      - '{{ wazuh_indexer_port | default("9200") }}:9200'
    volumes:
      - '{{ wazuh_indexer_data_vol }}:/var/lib/wazuh-indexer'
      - '{{ wazuh_indexer_tls_dir }}/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem'
      - '{{ wazuh_indexer_tls_dir }}/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key'
      - '{{ wazuh_indexer_tls_dir }}/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem'
      - '{{ wazuh_indexer_tls_dir }}/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem'
      - '{{ wazuh_indexer_tls_dir }}/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      OPENSEARCH_JAVA_OPTS: '-Xms1g -Xmx1g'
      PLUGINS_SECURITY_SYSTEM_INDICES_INDICES: >-
        '[".opendistro-alerting-config",'
        ' ".opendistro-alerting-alert*",'
        ' ".opendistro-anomaly-results*",'
        ' ".opendistro-anomaly-detector*",'
        ' ".opendistro-anomaly-checkpoints",'
        ' ".opendistro-anomaly-detection-state",'
        ' ".opendistro-reports-*",'
        ' ".opendistro-notifications-*",'
        ' ".opendistro-notebooks",'
        ' ".opensearch-observability",'
        ' ".opendistro-asynchronous-search-response*",'
        ' ".replication-metadata-store"]'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
        RestartSec=5
      - |
        [Install]
        WantedBy=default.target multi-user.target
