---
- name: Ensure Wazuh indexer is running
  become: true
  become_user: '{{ wazuh_indexer_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: '{{ wazuh_indexer_container }}'
    scope: user
