---
- name: Ensure Caddy is running
  become: true
  become_user: "{{ caddy_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: started
    name: "{{ caddy_container }}"
    scope: user
