---
- name: Ensure there's a volume to store manager api config
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_api_configuration_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager etc
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_etc_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager logs
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_logs_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager queue
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_queue_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager multigroups
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_var_multigroups_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager active response
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_active_response_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager agentless data
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_agentless_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager wodles
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_wodles_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager filebeat etc
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_filebeat_etc_vol }}'
    podman_user: '{{ wazuh_manager_user }}'

- name: Ensure there's a volume to store manager filebeat var
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ wazuh_manager_filebeat_var_vol }}'
    podman_user: '{{ wazuh_manager_user }}'
