---
- name: Volumes configuration
  ansible.builtin.import_tasks: volumes.yml
- name: Quadlet configuration
  ansible.builtin.import_tasks: quadlet.yml
- name: Services configuration
  ansible.builtin.import_tasks: services.yml
