---
- name: Ensure there's a volume to store Postgres Data
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: "{{ postgres_data_vol }}"
    podman_user: "{{ postgres_podman_user }}"
