- name: Configure bastion virtual machine
  hosts: bastion
  vars:
    bastion_user: bastion
    bastion_guacamole_network: guacamole
  tasks:
    - name: Ensure /etc/hosts is configured
      ansible.builtin.import_role:
        name: dynamic_hosts

    - name: Ensure there's a virtual network for Apache Guacamole
      ansible.builtin.import_role:
        name: podman
        tasks_from: network
      vars:
        podman_network: '{{ bastion_guacamole_network }}'
        podman_user: '{{ bastion_user }}'

    - name: Deploy Guacamole guacd
      ansible.builtin.import_role:
        name: guacamole_guacd
      vars:
        guacamole_guacd_user: '{{ bastion_user }}'
        guacamole_guacd_container: guacamole_guacd
        guacamole_guacd_network: '{{ bastion_guacamole_network }}'

    - name: Deploy Guacamole web
      ansible.builtin.import_role:
        name: guacamole_web
      vars:
        guacamole_web_user: '{{ bastion_user }}'
        guacamole_web_port: '8081'
        guacamole_web_container: guacamole_web
        guacamole_web_network: '{{ bastion_guacamole_network }}'
        guacamole_web_guacd_hostname: guacamole_guacd
        guacamole_web_extension_priority: 'openid'
        guacamole_web_openid_authorization_endpoint: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}/protocol/openid-connect/auth'
        guacamole_web_openid_jwks_endpoint: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}/protocol/openid-connect/certs'
        guacamole_web_openid_issuer: 'https://{{ auth_host }}.{{ internet_host }}/realms/{{ homelab_realm }}'
        guacamole_web_openid_client_id: '{{ remote_client }}'
        guacamole_web_openid_redirect_uri: 'https://{{ remote_host }}.{{ internet_host }}'
