- name: Configure virtual machines DNS server
  hosts: dns
  tasks:
    
    - name: Generate blocky_custom_records map
      set_fact:
        dns_records: >-
          {% set custom_records = {} %}
          {%- for service_name, service_config in homelab_services.items() %}
          - service_name: {{ service_name }}
            service_config: {{ service_config }}
            host: {{ service_config.host }}
            ip: {{ service_config.ip }}
            internet_host: {{ internet_host }}
            key: "{{ service_config.host }}.{{ internet_host }}"
            {% set custom_records = custom_records | combine({(service_config.host + '.' + internet_host): service_config.ip}) %}
          {%- endfor %}
          final_records: {{ custom_records }}
        
    - name: Debug
      ansible.builtin.debug:
        msg: '{{ dns_records  }}'

    - name: Deploy Blocky DNS Server
      ansible.builtin.import_role:
        name: blocky
      vars:
        blocky_user: '{{ dns_user }}'
        blocky_container: 'blocky'
        blocky_custom_records: '{{ dns_records }}'
        blocky_config_dir: '/var/blocky'
        blocky_dns_port: '53'
        blocky_http_port: '4000'
        blocky_upstreams:
          - '1.1.1.1'
          - '8.8.8.8'
        blocky_adlists:
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/fake.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads.txt'
        blocky_security_lists:
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt'
          # - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.amazon.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.apple.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.huawei.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.winoffice.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.samsung.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok.extended.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.lgwebos.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.roku.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.vivo.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.oppo-realme-onlydomains.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.xiaomi.txt'
