- name: Configure hypervisor(s)
  hosts: hypervisors
  tasks:
    - name: Network Interfaces configuration
      ansible.builtin.import_role:
        name: static_nics
      vars:
        static_nics_map: '{{ hypervisor_interfaces }}'

    - name: Powertop configuration
      ansible.builtin.import_role:
        name: powertop

    - name: Cockpit configuration
      ansible.builtin.import_role:
        name: cockpit

    - name: OpenRGB configuration
      ansible.builtin.import_role:
        name: openrgb

    - name: Incus configuration
      ansible.builtin.import_role:
        name: incus_server
