- name: Configure reverse proxy
  hosts: reverse_proxy
  vars:
    reverse_proxy_user: reverse-proxy
    reverse_proxy_network: reverse-proxy
  tasks:

    - name: Ensure there's a virtual network for reverse-proxy
      ansible.builtin.import_role:
        name: podman
        tasks_from: network
      vars:
        podman_network: '{{ reverse_proxy_network }}'
        podman_user: '{{ reverse_proxy_user }}'

    - name: Deploy Caddy
      ansible.builtin.import_role:
        name: caddy
      vars:
        caddy_user: "{{ reverse_proxy_user }}"
        caddy_container: caddy
        caddy_opt: caddy_opt
        caddy_tls: caddy_tls
        caddy_conf: /etc/Caddyfile
        caddy_internet_facing: false
        caddy_networks: '{{ reverse_proxy_network }}'

    - name: Deploy Tailscale private reverse proxy client
      ansible.builtin.import_role:
        name: tailscale_client
      vars:
        tailscale_client_user: '{{ reverse_proxy_user }}'
        tailscale_client_container: 'tailscale_client_private_reverse_proxy'
        tailscale_client_networks: '{{ reverse_proxy_network }}'
        tailscale_client_state_vol: 'tailscale_client_private_reverse_proxy_state'
        tailscale_client_accept_dns: 'false'
        tailscale_client_authkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33646531653433303136626133343035333932633830623533346361316463383365353636666334
          6330643233643132333737646161323935363962353163310a663165356362383434363263376263
          34663863353163373734313863373739353733333035383231363238306631653532623731323731
          6232623037353865320a333163663238653137393666653737366138313064326365303533653136
          33633765323438323266393934323037326265373937336336636530343561376136363164383533
          36316134396364346231366662356236653962353432356339343830633564666363373231666535
          616237323432363231323037353439613031
        tailscale_client_hostname: 'private-reverse-proxy'
        # tailscale_client_dest_ip: '{{ vps_adblock_ip }}'
        tailscale_client_userspace: 'false'

    - name: Deploy Wazuh agent
      ansible.builtin.import_role:
        name: wazuh_agent
      vars:
        wazuh_agent_version: '4.x'
        wazuh_agent_manager_host: '{{ siem_host }}'
        wazuh_agent_registration_pass: '{{ siem_enrollment_pass }}'
        wazuh_agent_name: 'reverse_proxy'
        wazuh_agent_groups: 'internet_facing,trusted'
