- name: Configure virtual machines DNS server
  hosts: vmdns
  vars:
    vm_dns_user: 'dns'
  tasks:
    - name: Deploy Blocky DNS Server
      ansible.builtin.import_role:
        name: blocky
      vars:
        blocky_user: '{{ vm_dns_user }}'
        blocky_container: 'blocky'
        blocky_config_dir: '/var/blocky'
        blocky_dns_port: '53'
        blocky_http_port: '4000'
