- name: Configure Virtual Private Server
  hosts: vps
  vars:
    vps_user: 'vps-hetzner'
    vps_reverse_proxy_network: 'vps_reverse_proxy'
    vps_adblock_network: 'vps_adblock'
  tasks:

    - name: Ensure there's a virtual network for VPS reverse proxy
      ansible.builtin.import_role:
        name: podman
        tasks_from: network
      vars:
        podman_network: '{{ vps_reverse_proxy_network }}'
        podman_user: '{{ vps_user }}'

    - name: Ensure there's a virtual network for VPS adblock
      ansible.builtin.import_role:
        name: podman
        tasks_from: network
      vars:
        podman_network: '{{ vps_adblock_network }}'
        podman_user: '{{ vps_user }}'

    - name: Deploy Headscale control server
      ansible.builtin.import_role:
        name: headscale
      vars:
        headscale_user: '{{ vps_user }}'
        headscale_container: 'headscale'
        headscale_command: 'serve'
        headscale_http_port: '8080'
        headscale_metrics_port: '9090'
        headscale_network: '{{ vps_reverse_proxy_network }}'
        headscale_conf_dir: '/var/headscale'
        headscale_tls_vol: 'headscale_tls'
        headscale_server_host: '{{ vpn_host }}.{{ internet_host }}'
        headscale_server_port: '443'
        headscale_listen_host: '0.0.0.0'
        headscale_listen_port: '8080'
        headscale_metrics_host: '0.0.0.0'
        headscale_grpc_listen_addr: '0.0.0.0'
        headscale_grpc_listen_port: '50443'
        headscale_dns_base_domain: 'nodes.{{ vpn_host }}.{{ internet_host }}'

    - name: Deploy internet facing Caddy
      ansible.builtin.import_role:
        name: caddy
      vars:
        caddy_user: '{{ vps_user }}'
        caddy_networks: '{{ vps_reverse_proxy_network }}'
        caddy_opt: caddy_opt
        caddy_tls: caddy_tls
        caddy_conf: /etc/Caddyfile
        caddy_internet_facing: true

    - name: Deploy Blocky DNS Server
      ansible.builtin.import_role:
        name: blocky
      vars:
        blocky_user: '{{ vps_user }}'
        blocky_container: 'blocky'
        blocky_config_dir: '/var/blocky'
        blocky_dns_port: '53'
        blocky_http_port: '4000'
        blocky_networks: '{{ vps_adblock_network }}'
        blocky_container_ip: '10.89.2.3'
        blocky_upstreams:
          - '1.1.1.1'
          - '8.8.8.8'
        blocky_adlists:
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/fake.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads.txt'
        blocky_security_lists:
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt'

    - name: Deploy Tailscale adblock client
      ansible.builtin.import_role:
        name: tailscale_client
      vars:
        tailscale_client_user: '{{ vps_user }}'
        tailscale_client_container: 'tailscale_client_adblock'
        tailscale_client_networks: '{{ vps_adblock_network }}'
        tailscale_client_state_vol: 'tailscale_client_adblock_state'
        tailscale_client_accept_dns: 'false'
        tailscale_client_authkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30356264363533313934313139313631376330366530666634376534646366333135373763363835
          6333643634623332326536393466396130643934333635650a373938366134366338343961633439
          30313933353234306363373562303031653734376239376266633263626166376663346337623566
          6330316665653336630a303038663763616664613466393734363763663738353832633634363632
          61336334623531383862323833613965656535363039383130393762633263666135623366366135
          62363166653663326331306438353562343130356130393036366364633365393661393135363763
          643633353163336637366635383562383934
        tailscale_client_hostname: 'adblock-dns'
        tailscale_client_dest_ip: '10.89.2.3'
        tailscale_client_userspace: 'false'
