- name: Configure Virtual Private Server
  hosts: vps
  vars:
    vps_user: 'vps-hetzner'
    vps_network: 'vps'
  tasks:

    - name: Ensure there's a virtual network for VPS services
      ansible.builtin.import_role:
        name: podman
        tasks_from: network
      vars:
        podman_network: '{{ vps_network }}'
        podman_user: '{{ vps_user }}'

    - name: Deploy Headscale
      ansible.builtin.import_role:
        name: headscale
      vars:
        headscale_user: '{{ vps_user }}'
        headscale_container: 'headscale'
        headscale_command: 'serve'
        headscale_http_port: '8080'
        headscale_metrics_port: '9090'
        headscale_network: '{{ vps_network }}'
        headscale_conf_dir: '/var/headscale'
        headscale_tls_vol: 'headscale_tls'
        headscale_server_host: '{{ vpn_host }}.{{ internet_host }}'
        headscale_server_port: '443'
        headscale_listen_host: '0.0.0.0'
        headscale_listen_port: '8080'
        headscale_metrics_host: '0.0.0.0'
        headscale_grpc_listen_addr: '0.0.0.0'
        headscale_grpc_listen_port: '50443'
        headscale_dns_base_domain: 'nodes.{{ vpn_host }}.{{ internet_host }}'

    - name: Deploy internet facing Caddy
      ansible.builtin.import_role:
        name: caddy
      vars:
        caddy_user: '{{ vps_user }}'
        caddy_networks: '{{ vps_network }}'
        caddy_opt: caddy_opt
        caddy_tls: caddy_tls
        caddy_conf: /etc/Caddyfile
        caddy_internet_facing: true

    - name: Deploy Blocky DNS Server
      ansible.builtin.import_role:
        name: blocky
      vars:
        blocky_user: '{{ vps_user }}'
        blocky_container: 'blocky'
        blocky_config_dir: '/var/blocky'
        blocky_dns_port: '53'
        blocky_http_port: '4000'
        blocky_upstreams:
          - '1.1.1.1'
          - '8.8.8.8'
        blocky_adlists:
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/fake.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads.txt'
        blocky_security_lists:
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt'
