- name: Zram configuration
  hosts: all
  vars:
    sysctl_config:
      vm.swappiness: 180
      vm.watermark_boost_factor: 0
      vm.watermark_scale_factor: 125
      vm.page-cluster: 0

  tasks:
    - name: Configure Zram sysctl values
      ansible.builtin.import_role:
        name: zram
    - name: Set Zram values
      become: true
      ansible.posix.sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        state: present
      with_dict: '{{ sysctl_config }}'

    - name: Restart systemd-sysctl
      become: true
      ansible.builtin.systemd_service:
        daemon_reload: true
        state: restarted
        name: 'systemd-sysctl'
