---
- name: Ensure there's a volume to store Trilium Next data
  ansible.builtin.import_role:
    name: podman
    tasks_from: local_volume
  vars:
    podman_local_volume: '{{ trilium_data }}'
    podman_user: '{{ trilium_user }}'
