---
- name: Ensure dependencies to install VMWare are met
  become: true
  ansible.builtin.package:
    name:
      - build-essential
      - linux-headers-{{ ansible_kernel }}
      - gnome-session
      - gnome-session-common
      - gnome-shell
      - gnome-terminal
      - nautilus
      - file-roller
    state: present
