---
- name: Restart wikijs
  become: true
  become_user: "{{ wikijs_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ wikijs_container }}"
    scope: user

- name: Restart MariaDB
  become: true
  become_user: "{{ wikijs_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ wikijs_mariadb_container }}"
    scope: user
