- name: Ensure incus can mount lvm storage
  become: true
  ansible.builtin.package:
    name:
      - lvm2
    state: present

- name: Ensure Open Virtual Network Switch packages are installed
  become: true
  ansible.builtin.apt:
    name: qemu-system
    state: present
    default_release: bookworm-backports
    update_cache: true

- name: Ensure Incus is installed and updated
  become: true
  ansible.builtin.apt:
    name: incus
    state: present
    default_release: bookworm-backports
    update_cache: true

- name: Ensure Open Virtual Network packages are installed
  become: true
  ansible.builtin.apt:
    pkg:
      - ovn-host
      - ovn-central
    state: present
    default_release: bookworm-backports
    update_cache: true
